services:
  openclaw:
    image: ghcr.io/openclaw/openclaw
    container_name: openclaw
    restart: unless-stopped

    env_file:
      - .env

    environment:
      HOME: /home/node
      XDG_CONFIG_HOME: /home/node/.openclaw
      OPENCLAW_HOME: /home/node/.openclaw
      OPENCLAW_STATE_DIR: /home/node/.openclaw

    ports:
      - "127.0.0.1:18789:18789"

    volumes:
      - /srv/openclaw/state:/home/node/.openclaw
      - /srv/openclaw/workspace:/home/node/.openclaw/workspace

    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: /aws/ec2/claw/openclaw
        awslogs-stream: openclaw
        awslogs-create-group: "false"

    security_opt:
      - no-new-privileges:true

    tmpfs:
      - /tmp:rw,nosuid,nodev,noexec,size=512m

  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    depends_on:
      - openclaw
    network_mode: host
    env_file:
      - .env
    command: tunnel --no-autoupdate --edge-ip-version 6 --protocol http2 run
