services:
  claw:
    image: alpine/openclaw
    container_name: claw
    restart: unless-stopped
    env_file: [.env]
    # environment:
    # - OPENCLAW_ALLOW_INSECURE_PRIVATE_WS=true
    # - OPENCLAW_DOCKER_APT_PACKAGES=git
    # - OPENCLAW_INSTALL_BROWSER=true
    # - OPENCLAW_INSTALL_DOCKER_CLI=true
    ports:
      - "18789:18789" # gateway
      # - "18790:18790" # bridge
    volumes:
      - ./config:/home/node/.openclaw
      - ./init.mjs:/app/init.mjs
      - ./openclaw.json.tmpl:/home/node/.openclaw/openclaw.json.tmpl
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: /aws/ec2/claw/openclaw
        awslogs-stream: openclaw
        awslogs-create-group: "false"
    security_opt:
      - no-new-privileges:true
    command: node init.mjs
    # only thing manually needed is gateway token & pairing device


  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    network_mode: host
    env_file: [.env]
    command: tunnel --no-autoupdate --edge-ip-version 6 --protocol http2 run
