services:
  claw:
    image: alpine/openclaw
    container_name: claw
    restart: unless-stopped
    user: 1000:1000
    env_file: [.env]
    ports:
      - "18789:18789" # gateway
      # - "18790:18790" # bridge
    volumes:
      - ./config:/home/node/.openclaw
      - ./init.mjs:/app/init.mjs:ro
      - ./skills:/app/skills:ro
      - ./openclaw.json.tmpl:/home/node/.openclaw/openclaw.json.tmpl:ro
      - ./auth-profiles.json.tmpl:/home/node/.openclaw/auth-profiles.json.tmpl:ro
    logging:
      driver: awslogs
      options:
        awslogs-region: us-east-1
        awslogs-group: /aws/ec2/claw/openclaw
        awslogs-stream: openclaw
        awslogs-create-group: "false"
        awslogs-endpoint: https://logs.us-east-1.api.aws
    security_opt:
      - no-new-privileges:true
    command: node init.mjs
# approve the first device pending
# docker exec claw bash -lc 'openclaw devices approve $(openclaw devices list | grep -m1 -oE "[0-9a-fA-F-]{36}")'


  cloudflared:
    image: cloudflare/cloudflared
    container_name: cloudflared
    restart: unless-stopped
    network_mode: host
    env_file: [.env]
    command: tunnel --no-autoupdate --edge-ip-version 6 --protocol http2 run
