permissions: # required for oidc
  id-token: write
  contents: read
on:
  push:
    branchs:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Extract Pipline Vars
        run: |
          repo=${GITHUB_REPOSITORY#CodaBool/}
          echo "run=${RUN_NUMBER}" >> $GITHUB_ENV
          echo "repo=${repo,,}" >> $GITHUB_ENV
        env:
          RUN_NUMBER: ${{ toJSON(github.run_number) }}
      # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::919759177803:role/gh-action-assume
          aws-region: us-east-1
      # https://github.com/marketplace/actions/setup-hashicorp-packer
      - uses: hashicorp/setup-packer@main
        with:
          version: 1.15.0 # https://releases.hashicorp.com/packer

      - name: Write env
        run: |
          cat > ami/.env <<'EOF'
          TUNNEL_TOKEN=${{ secrets.TUNNEL_TOKEN }}
          OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }}
          GOOGLE_API_KEY=${{ secrets.GOOGLE_API_KEY }}
          OPENCLAW_GATEWAY_TOKEN=${{ secrets.OPENCLAW_GATEWAY_TOKEN }}
          BRAVE_TOKEN=${{ secrets.BRAVE_TOKEN }}
          DISCORD_TOKEN=${{ secrets.DISCORD_TOKEN }}
          DISCORD_USER=${{ secrets.DISCORD_USER }}
          EOF
      - name: Packer
        if: "! contains(github.event.commits[0].message, '[skip build]')"
        run: |
          ./download_compose.sh
          packer init .
          packer build -var="unique_ami_name=claw" .
      # https://github.com/marketplace/actions/hashicorp-setup-terraform
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6 # https://releases.hashicorp.com/terraform
          # terraform_wrapper: false
      - name: Deploy
        run: |
          terraform init
          terraform apply -auto-approve
