permissions: # required for oidc
  id-token: write
  contents: read
on:
  push:
    branchs:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Extract Pipline Vars
        run: |
          repo=${GITHUB_REPOSITORY#CodaBool/}
          echo "run=${RUN_NUMBER}" >> $GITHUB_ENV
          echo "repo=${repo,,}" >> $GITHUB_ENV
        env:
          RUN_NUMBER: ${{ toJSON(github.run_number) }}
      # https://github.com/marketplace/actions/configure-aws-credentials-action-for-github-actions
      - uses: aws-actions/configure-aws-credentials@v6
        with:
          role-to-assume: arn:aws:iam::919759177803:role/gh-action-assume
          aws-region: us-east-1
      # https://github.com/marketplace/actions/setup-hashicorp-packer
      - uses: hashicorp/setup-packer@main
        with:
          version: 1.15.0 # https://releases.hashicorp.com/packer
      - name: Packer
        if: "! contains(github.event.commits[0].message, '[skip build]')"
        # working-directory: ./ops
        run: |
          # echo "MONGO_URI=${{ secrets.MONGO_URI }}" > ../.env
          ./download_compose.sh
          packer init .
          packer build -var="unique_ami_name=claw" .
          #packer build -var="unique_ami_name=${{ env.repo }}-${{ env.run }}" .
      # https://github.com/marketplace/actions/hashicorp-setup-terraform
      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.14.6 # https://releases.hashicorp.com/terraform
          # terraform_wrapper: false
      - name: Deploy
        # working-directory: ./ops
        run: |
          terraform init
          terraform apply -auto-approve
          # terraform apply -auto-approve -var="ssh_ip=${{ secrets.WIN_IP }}"
      # - name: Dashboard
      #   working-directory: ./ops
      #   run: |
      #     ./dashboard.sh
      #     ./rm_ami.sh || true
      #     ./rm_ebs.sh || true
      # - name: Tag
      #   working-directory: ./ops
      #   run: aws ec2 create-tags --resources $(terraform output -raw id) --tags Key=Name,Value=${{ env.repo }}
